[package]
name = "vexel"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
nom = "8.0.0-beta.1"
bytes = "1.9.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde_json = "1.0"
tiny_http = "0.12"
